//
// This file was generated by the JPA Modeler
//
package Lab5.Entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

@Entity
public class Book implements Serializable {

    @OneToOne(targetEntity = Publication.class)
    private Publication publication;

    @Basic
    private String Author;

    public Book() {

    }

    public Publication getPublication() {
        return this.publication;
    }

    public void setPublication(Publication publication) {
        this.publication = publication;
    }

    public String getAuthor() {
        return this.Author;
    }

    public void setAuthor(String Author) {
        this.Author = Author;
    }
}
