//
// This file was generated by the JPA Modeler
//
package Lab5.Entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.OneToOne;

@Entity
public class Magazine implements Serializable {

    @Basic
    private String OrderQTY;

    @OneToOne(targetEntity = Publication.class)
    private Publication publication;

    @Basic
    private String currIssue;

    public Magazine() {

    }

    public String getOrderQTY() {
        return this.OrderQTY;
    }

    public void setOrderQTY(String OrderQTY) {
        this.OrderQTY = OrderQTY;
    }

    public Publication getPublication() {
        return this.publication;
    }

    public void setPublication(Publication publication) {
        this.publication = publication;
    }

    public String getCurrIssue() {
        return this.currIssue;
    }

    public void setCurrIssue(String currIssue) {
        this.currIssue = currIssue;
    }
}
