//
// This file was generated by the JPA Modeler
//
package Lab5.Entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;

@Entity
public abstract class Publication implements Serializable {

    @Basic
    private String Price;

    @Basic
    private String Copies;

    @Basic
    private String Title;

    public Publication() {

    }

    public String getPrice() {
        return this.Price;
    }

    public void setPrice(String Price) {
        this.Price = Price;
    }

    public String getCopies() {
        return this.Copies;
    }

    public void setCopies(String Copies) {
        this.Copies = Copies;
    }

    public String getTitle() {
        return this.Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }
}
